# Generated by Django 6.0.3 on 2026-05-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_presenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
